### ISSUE TITLE
Starting suite through run.sh stops with error

### ISSUE THREAD

**Issue by dminor** [mozilla-b2g/fxos-certsuite#26]
It appears we are not packaging the bundles directory:

Traceback (most recent call last):
  File "/home/dminor/src/2fxos-certsuite/certsuite_venv/bin/runcertsuite", line 8, in <module>
    load_entry_point('fxos-certsuite==0.1', 'console_scripts', 'runcertsuite')()
  File "/home/dminor/src/2fxos-certsuite/certsuite_venv/local/lib/python2.7/site-packages/fxos_certsuite-0.1-py2.7.egg/certsuite/harness.py", line 116, in main
    install_marionette(args.version)
  File "/home/dminor/src/2fxos-certsuite/certsuite_venv/local/lib/python2.7/site-packages/fxos_certsuite-0.1-py2.7.egg/certsuite/harness.py", line 100, in install_marionette
    cwd=script_dir)
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/home/dminor/src/2fxos-certsuite/certsuite_venv/local/lib/python2.7/site-packages/fxos_certsuite-0.1-py2.7.egg/bundles/1.3'

**Comment by ypwalter** [comment]
I will assume this issue is out-of-dated. I will open a new issue once I find the same issue.
@ShakoHo , please help me with closing these issue.
