### ISSUE TITLE
V2.1 pulled conflicted version

### ISSUE THREAD

**Issue by ypwalter** [mozilla-b2g/fxos-certsuite#315]
> python setup.py install

Installed /home/wachen/FirefoxOS/fxos-certsuite2/.mcts_v210/lib/python2.7/site-packages/plivo-0.9.6-py2.7.egg
error: Installed distribution marionette-client 0.7.10 conflicts with requirement marionette-client>=0.16

>pip install marionette-client==0.16
>runcertsuite

Traceback (most recent call last):
  File "/home/wachen/FirefoxOS/fxos-certsuite2/.mcts_v210/bin/runcertsuite", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/wachen/FirefoxOS/fxos-certsuite2/.mcts_v210/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2711, in <module>
    parse_requirements(__requires__), Environment()
  File "/home/wachen/FirefoxOS/fxos-certsuite2/.mcts_v210/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: marionette-client==0.7.10

There is something wrong with the dependency. We need to figure that out before it crashes on partners.

**Comment by ypwalter** [comment]
I think making 
fxos-appgen == 0.11
in requirement.txt might work
